#______________________________________________________________________________
# This controls general settings for the file manager
[manager]

# Show hidden files
show_hidden = true

#______________________________________________________________________________

# This is where you list programs that can open files
[opener]
nvim = [
    # This will open a new Ghostty terminal and then, 
    # use Neovim to open the file
    # `ophan = true` just means that the program should 
    # open in a separate terminal.
    { run = 'ghostty nvim "$@"', orphan = true, for = "unix" }
]

vlc = [
    # This will launch VLC to open media files
    { run = 'vlc "$@"', orphan = true, for = "unix" }
]

firefox = [
    # This will launch VLC to open media files
    { run = 'firefox "$@"', orphan = true, for = "unix" }
]

viewnior = [
    # This will launch Vienoir to open media files
    { run = 'viewnior "$@"', orphan = true, for = "unix" }
]

# This is where you define what programs yazi 
# should use to open certain file types
[open]
rules = [
    # Document Files
    { name = "*.md", use = "nvim" },
    { name = "*.pdf", use = "firefox" },

    # Music Files
    { name = "*.mp3", use = "vlc" },

    # Video Files
    { name = "*.mp4", use = "vlc" },
    { name = "*.mpeg", use = "vlc" },
    { name = "*.mkv", use = "vlc" },

    # Image Files
    { name = "*.png", use = "viewnior" },
    { name = "*.jpg", use = "viewnior" },
    { name = "*.jpeg", use = "viewnior" },

    # Web pages
    { name = "*.html", use = "firefox" },
    { name = "*.url", use = "firefox" }
]

#______________________________________________________________________________
